### ISSUE TITLE
Still getting issues with faces on certain characters

### ISSUE THREAD

**Issue by zachHixson** [GhostlyDark/MM-Reloaded-2S2H#2]
Despite it being reported as resolved in the other issue, I'm still getting problems with certain faces such as the Happy Mask Salesman which look like barcodes.

The first time I generated the OTR I messed it up and all the faces were like that, but after regenerating a new OTR following the proper instructions on the main page of the repository, Link's face is fixed as well as a few others around Clock Town, but plenty of others like the HMS and the orange fairy are still messed up.

Am I doing something wrong? Is there a way to fix this?

**Comment by GhostlyDark** [comment]
Use a build from this PR or a WIP build once it is merged:
https://github.com/HarbourMasters/2ship2harkinian/pull/794

The fix must be present in 2Ship, as it is not a pack issue. The upcoming v1.1.0 release should be good.

> The first time I generated the OTR I messed it up and all the faces were like that, but after regenerating a new OTR following the proper instructions on the main page of the repository, Link's face is fixed as well as a few others around Clock Town, but plenty of others like the HMS and the orange fairy are still messed up.

Does this happen with the 2Ship build I linked to?

**Comment by zachHixson** [comment]
Thanks! Works great!
